import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { distribute } from "./engine.ts";
import {
  allocations,
  applicantByInitiative,
  donations,
  members,
  round,
  viewerId,
} from "./dataset.ts";

const result = distribute(round, members, allocations, donations);
const shareById = new Map(result.members.map((m) => [m.memberId, m]));

// Per-initiative supporters (members who allocated to it), for the
// "Projekt-Mitglieder" screen.
const supporters: Record<string, Array<{ memberId: string; amount: number }>> = {};
for (const i of round.initiatives) supporters[i.id] = [];
for (const a of allocations) supporters[a.initiativeId].push({ memberId: a.memberId, amount: a.amount });
for (const id of Object.keys(supporters)) supporters[id].sort((x, y) => y.amount - x.amount);

// Per-member allocations, for profile + ballot screens.
const allocationsByMember: Record<string, Array<{ initiativeId: string; amount: number }>> = {};
for (const a of allocations) {
  (allocationsByMember[a.memberId] ??= []).push({ initiativeId: a.initiativeId, amount: a.amount });
}

const view = {
  account: {
    name: "Initiativkonto für selbstbestimmtes Handeln durch Gegenseitigkeit",
    bank: "GLS Gemeinschaftsbank eG",
    note: "Beispieldaten — keine echten Personen- oder Kontodaten.",
  },
  round: {
    id: round.id,
    label: round.label,
    date: round.date,
    totalBalance: round.totalBalance,
    sharePerMember: result.members[0]?.share ?? 0,
    eligibleCount: members.filter((m) => m.voteEligible).length,
    memberCount: members.length,
    votedCount: result.members.filter((m) => m.allocated > 0).length,
  },
  viewerId,
  members: members.map((m) => ({
    id: m.id,
    name: m.name,
    city: m.city,
    joinedAt: m.joinedAt,
    voteEligible: m.voteEligible,
    monthly: m.contribution.monthly,
    paidSinceJan: m.contribution.paidSinceJan,
    balance: m.contribution.balance,
    freeDonation: m.contribution.freeDonation,
    share: shareById.get(m.id)?.share ?? 0,
    allocated: shareById.get(m.id)?.allocated ?? 0,
    remaining: shareById.get(m.id)?.remaining ?? 0,
    allocations: allocationsByMember[m.id] ?? [],
  })),
  initiatives: round.initiatives.map((i) => {
    const o = result.initiatives.find((x) => x.initiativeId === i.id)!;
    return {
      id: i.id,
      title: i.title,
      description: i.description ?? "",
      fund: i.fund ?? null,
      applicantId: applicantByInitiative[i.id] ?? null,
      fromShares: o.fromShares,
      fromDonations: o.fromDonations,
      total: o.total,
      supporters: supporters[i.id],
    };
  }),
  result: {
    carryOver: result.carryOver,
    totalToInitiatives: result.totalToInitiatives,
    totalDonations: result.totalDonations,
  },
};

const outDir = join(dirname(fileURLToPath(import.meta.url)), "..", "ui");
const outFile = join(outDir, "dataset.js");
writeFileSync(
  outFile,
  `// AUTO-GENERATED by src/generate-ui-data.ts — do not edit by hand.\n` +
    `window.DATASET = ${JSON.stringify(view, null, 2)};\n`,
);
console.log(`Wrote ${outFile}`);
console.log(
  `  ${view.members.length} Mitglieder, ${view.round.votedCount} abgestimmt, ` +
    `${view.initiatives.length} Initiativen, Anteil ${view.round.sharePerMember / 100} €`,
);
